version: 2

sources:
  - name: ecom
    database: vast  
    schema: "tesseract/danadbtest"  
    tables:
      - name: raw_customers
      - name: raw_items
      - name: raw_orders
      - name: raw_products                              
      - name: raw_stores
      - name: raw_supplies